name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: packagecontrol/st-schema-reviewer-action@fd6e66ba493f47c0ce8f4e2cf1e138b4abaf6e48

  trigger-review:
    needs: tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger package review
        # continue-on-error: true
        run: curl --http1.1 -X POST https://packagecontrol.io/test_pr/$PR_NUM.json
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
